package weather

type WEATHERCODE string

/*http://weather.yukigesho.com/code.html*/
const (
    ClearWeather                          WEATHERCODE = "100" // 晴れ
    SunnyAndCloudy                        WEATHERCODE = "101" // 晴れ 時々 くもり
    ClearWithBriefRain                    WEATHERCODE = "102" // 晴れ 一時 雨
    ClearSometimesRain                    WEATHERCODE = "103" // 晴れ 時々 雨
    ClearWithBriefSnow                    WEATHERCODE = "104" // 晴れ 一時 雪
    ClearSometimesSnow                    WEATHERCODE = "105" // 晴れ 時々 雪
    ClearWithBriefRainOrSnow              WEATHERCODE = "106" // 晴れ 一時 雨か雪
    ClearSometimesRainOrSnow              WEATHERCODE = "107" // 晴れ 時々 雨か雪
    ClearWithBriefRainOrThunderstorms     WEATHERCODE = "108" // 晴れ 一時 雨か雷雨
    ClearSometimesRainOrThunderstorms     WEATHERCODE = "109" // 晴れ 時々 雨か雷雨
    ClearThenOccasionallyCloudy           WEATHERCODE = "110" // 晴れ のち時々くもり
    ClearThenCloudy                       WEATHERCODE = "111" // 晴れ のち くもり
    ClearThenBriefRain                    WEATHERCODE = "112" // 晴れ のち一時 雨
    ClearThenSometimesRain                WEATHERCODE = "113" // 晴れ のち時々 雨
    ClearThenRain                         WEATHERCODE = "114" // 晴れ のち 雨
    ClearThenBriefSnow                    WEATHERCODE = "115" // 晴れ のち一時 雪
    ClearThenSometimesSnow                WEATHERCODE = "116" // 晴れ のち時々 雪
    ClearThenSnow                         WEATHERCODE = "117" // 晴れ のち 雪
    ClearThenRainOrSnow                   WEATHERCODE = "118" // 晴れ のち 雨か雪
    ClearThenRainOrThunderstorms          WEATHERCODE = "119" // 晴れ のち 雨か雷雨
    ClearThenMorningEveningBriefRain      WEATHERCODE = "120" // 晴れ 朝夕 一時 雨
    ClearThenRainInTheMorning             WEATHERCODE = "121" // 晴れ 朝の内一時 雨
    ClearThenRainInTheEvening             WEATHERCODE = "122" // 晴れ 夕方一時 雨
    ClearAlongTheMountain                 WEATHERCODE = "123" // 晴れ 山沿い 雷雨
    ClearAlongTheMountainSnow             WEATHERCODE = "124" // 晴れ 山沿い 雪
    ThunderstormsInTheAfternoon           WEATHERCODE = "125" // 晴れ 午後は雷雨
    RainFromNoon                          WEATHERCODE = "126" // 晴れ 昼頃から雨
    RainFromEvening                       WEATHERCODE = "127" // 晴れ 夕方から雨
    RainAtNight                           WEATHERCODE = "128" // 晴れ 夜は雨
    RainFromMidnight                      WEATHERCODE = "129" // 晴れ 夜半から雨
    MorningFogThenClear                   WEATHERCODE = "130" // 朝の内 霧 後 晴れ
    MorningFog                            WEATHERCODE = "131" // 晴れ 明け方 霧
    MorningCloudsEveningClouds            WEATHERCODE = "132" // 晴れ 朝夕 くもり
    ClearSometimesRainWithThunderstorms   WEATHERCODE = "140" // 晴れ 時々 雨で雷を伴う
    ClearSometimesSnowOrRain              WEATHERCODE = "160" // 晴れ 一時 雪か雨
    SnowOrRainSometimes                   WEATHERCODE = "170" // 晴れ 時々 雪か雨
    SnowOrRainThen                        WEATHERCODE = "181" // 晴れ のち 雪か雨
    CloudyWeather                         WEATHERCODE = "200" // くもり
    CloudySometimesSunny                  WEATHERCODE = "201" // くもり 時々 晴れ
    CloudyWithBriefRain                   WEATHERCODE = "202" // くもり 一時 雨
    CloudySometimesRain                   WEATHERCODE = "203" // くもり 時々 雨
    CloudyWithBriefSnow                   WEATHERCODE = "204" // くもり 一時 雪
    CloudySometimesSnow                   WEATHERCODE = "205" // くもり 時々 雪
    CloudyWithBriefRainOrSnow             WEATHERCODE = "206" // くもり 一時 雨か雪
    CloudySometimesRainOrSnow             WEATHERCODE = "207" // くもり 時々 雨か雪
    CloudyWithBriefRainOrThunderstorms    WEATHERCODE = "208" // くもり 一時 雨か雷雨
    Mist                                  WEATHERCODE = "209" // 霧
    CloudyThenSometimesSunny              WEATHERCODE = "210" // くもり のち時々 晴れ
    CloudyThenSunny                       WEATHERCODE = "211" // くもり のち 晴れ
    CloudyThenBriefRain                   WEATHERCODE = "212" // くもり のち一時 雨
    CloudyThenSometimesRain               WEATHERCODE = "213" // くもり のち時々 雨
    CloudyThenRain                        WEATHERCODE = "214" // くもり のち 雨
    CloudyThenBriefSnow                   WEATHERCODE = "215" // くもり のち一時 雪
    CloudyThenSometimesSnow               WEATHERCODE = "216" // くもり の
	CloudyThenSnow              		  WEATHERCODE = "217" // くもり のち 雪
    CloudyThenRainOrSnow                  WEATHERCODE = "218" // くもり のち 雨か雪
    CloudyThenRainOrThunderstorms         WEATHERCODE = "219" // くもり のち 雨か雷雨
    CloudyMorningEveningBriefRain         WEATHERCODE = "220" // くもり 朝夕一時 雨
    CloudyMorningRain                     WEATHERCODE = "221" // くもり 朝の内一時 雨
    CloudyEveningBriefRain                WEATHERCODE = "222" // くもり 夕方一時 雨
    CloudyDuringTheDaySometimesSunny      WEATHERCODE = "223" // くもり 日中時々 晴れ
    CloudyFromAroundNoonRain              WEATHERCODE = "224" // くもり 昼頃から雨
    CloudyFromEveningRain                 WEATHERCODE = "225" // くもり 夕方から雨
    CloudyAtNightRain                     WEATHERCODE = "226" // くもり 夜は雨
    CloudyFromMidnightRain                WEATHERCODE = "227" // くもり 夜半から雨
    CloudyFromAroundNoonSnow              WEATHERCODE = "228" // くもり 昼頃から雪
    CloudyFromEveningSnow                 WEATHERCODE = "229" // くもり 夕方から雪
    CloudyAtNightSnow                     WEATHERCODE = "230" // くもり 夜は雪
    CloudyOverMarineAreasMistOrDrizzle    WEATHERCODE = "231" // くもり海上海岸は霧か霧雨
    CloudySometimesRainWithThunderstorms  WEATHERCODE = "240" // くもり 時々雨で 雷を伴う
    CloudySometimesSnowWithThunderstorms  WEATHERCODE = "250" // くもり 時々雪で 雷を伴う
    CloudyBrieflySnowOrRain               WEATHERCODE = "260" // くもり 一時 雪か雨
    CloudySometimesSnowOrRain             WEATHERCODE = "270" // くもり 時々 雪か雨
    CloudyThenSnowOrRain                  WEATHERCODE = "281" // くもり のち 雪か雨
	Rain                                  WEATHERCODE = "300" // 雨
	RainSometimesSunny                    WEATHERCODE = "301" // 雨 時々 晴れ
	RainSometimesStop                     WEATHERCODE = "302" // 雨 時々 止む
	RainSometimesSnow                     WEATHERCODE = "303" // 雨 時々 雪
	RainOrSnow                            WEATHERCODE = "304" // 雨か雪
	HeavyRain                             WEATHERCODE = "306" // 大雨
	StrongWindAndRain                     WEATHERCODE = "307" // 風雨共に強い
	RainWithStrongWinds                   WEATHERCODE = "308" // 雨で暴風を伴う
	RainBrieflyStop                       WEATHERCODE = "309" // 雨 一時 雪
	RainThenSunny                         WEATHERCODE = "311" // 雨 のち 晴れ
	RainThenCloudy                        WEATHERCODE = "313" // 雨 のち くもり
	RainThenSometimesSnow                 WEATHERCODE = "314" // 雨 のち時々 雪
	RainThenSnow                          WEATHERCODE = "315" // 雨 のち 雪
	RainOrSnowThenSunny                   WEATHERCODE = "316" // 雨か雪 のち 晴れ
	RainOrSnowThenCloudy                  WEATHERCODE = "317" // 雨か雪 のち くもり
	MorningRainThenSunny                  WEATHERCODE = "320" // 朝の内雨 のち 晴れ
	MorningRainThenCloudy                 WEATHERCODE = "321" // 朝の内雨 のち くもり
	RainMorningEveningBrieflySnow         WEATHERCODE = "322" // 雨 朝晩一時 雪
	RainFromNoonThenSunny                 WEATHERCODE = "323" // 雨 昼頃から 晴れ
	RainFromEveningThenSunny              WEATHERCODE = "324" // 雨 夕方から 晴れ
	RainAtNightThenClear                  WEATHERCODE = "325" // 雨 夜は晴
	RainFromEveningThenSnow               WEATHERCODE = "326" // 雨 夕方から雪
	RainAtNightThenSnow                   WEATHERCODE = "327" // 雨 夜は雪
	RainBrieflyHeavy                      WEATHERCODE = "328" // 雨 一時強く降る
	RainBrieflySleet                      WEATHERCODE = "329" // 雨 一時 みぞれ
	SnowOrRain                            WEATHERCODE = "340" // 雪か雨
	RainWithThunder                       WEATHERCODE = "350" // 雨で雷を伴う
	SnowOrRainThenSunny                   WEATHERCODE = "361" // 雪か雨 のち 晴れ
	SnowOrRainThenCloudy                  WEATHERCODE = "371" // 雪か雨 のち くもり
	Snow                                  WEATHERCODE = "400" // 雪
	SnowSometimesSunny                    WEATHERCODE = "401" // 雪 時々 晴れ
	SnowSometimesStop                     WEATHERCODE = "402" // 雪 時々止む
	SnowSometimesRain                     WEATHERCODE = "403" // 雪 時々 雨
	HeavySnow                             WEATHERCODE = "405" // 大雪
	StrongWindAndSnow                     WEATHERCODE = "406" // 風雪強い
    Snowstorm                             WEATHERCODE = "407" // 暴風雪
    SnowBrieflyRain                       WEATHERCODE = "409" // 雪 一時 雨
	SnowThenSunny                         WEATHERCODE = "411" // 雪 のち 晴れ
    SnowThenCloudy                        WEATHERCODE = "413" // 雪 のち くもり
    SnowThenRain                          WEATHERCODE = "414" // 雪 のち 雨
    MorningSnowThenSunny                  WEATHERCODE = "420" // 朝の内雪 のち 晴れ
    MorningSnowThenCloudy                 WEATHERCODE = "421" // 朝の内雪 のち くもり
    SnowFromAroundNoonThenRain            WEATHERCODE = "422" // 雪 昼頃から雨
    SnowFromEveningThenRain               WEATHERCODE = "423" // 雪 夕方から雨
    SnowFromMidnightThenRain              WEATHERCODE = "424" // 雪 夜半から雨
    SnowBrieflyHeavy                      WEATHERCODE = "425" // 雪 一時強く降る
    SnowThenSleet                         WEATHERCODE = "426" // 雪 のち みぞれ
    SnowBrieflySleet                      WEATHERCODE = "427" // 雪 一時 みぞれ
    SnowWithThunder                       WEATHERCODE = "450" // 雪で雷を伴う
)